/*
 * whitelist.js: lists of whitelisted domain names
 *
 * (C) 2012 Ayatii Limited
 *
 */


Blacklist = module.exports;

Blacklist.safeDomains = [
  , 'amazon.ca'
  , 'amazon.cn'
  , 'amazon.com'
  , 'amazon.com.br'
  , 'amazon.co.uk'
  , 'amazon.de'
  , 'amazon.fr'
  , 'amazon.it'
  , 'amazon.jp'
  , 'amazon.es'
  , 'apple.com'
  , 'apunkachoice.com'
  , 'answers.yahoo.com'
  , 'beforeitsnews.com'
  , 'bharatmovies.com'
  , 'bollymeaning.com'
  , 'bollywoodhungama.com'
  , 'books.google.com'
  , 'craftkeys.com'
  , 'deviantart.com'
  , 'entertainment.oneindia.in'
  , 'hindustantimes.com'
  , 'glamsham.com'
  , 'flipkart.com'
  , 'imdb.com'
  , 'india-forums.com'
  , 'indicine.com'
  , 'intoday.in'
  , 'kexp.org'
  , 'koimoi.com'
  , 'last.fm'
  , 'melodytracks.com'
  , 'music.ovi.com'
  , 'msn.com'
  , 'planetbollywood.com'
  , 'ndtv.com'
  , 'nytimes.com'
  , 'ovi.com'
  , 'saavn.com'
  , 'songson.net'
  , 'spotify.com'
  , 'ww.smashits.com'
  , 'timesofindia.indiatimes.com'
  , 'raaga.com'
  , 'rdio.com'
  , 'rottentomatoes.com'
  , 'webstatsdomain.com'
  , 'wikipedia.org'
  , 'en.wikipedia.org'
  , 'lastfm.it'
  , '7digital.com'
  , 'roughtrade.com'
  , 'bleep.com'
  , 'mixmag.net'
  , 'deezer.com'
  , 'boomkat.com'
  , 'play.com'
  , 'we7.com'
  , 'music.sonyentertainmentnetwork.com'
  , 'virginmega.fr'
  , 'emusic.com'
  , 'normanrecords.com'
  , 'lyrics4song.com'
  , 'slacker.com'
  , 'rhapsody.com'
  , 'play.google.com'
  , 'music.nokia.com'
  , 'music.ovi.com'
  , 'itunes.apple.com'
  , 'junodownload.com'
  , 'thequietus.com'
  , 'discogs.com'
  , 'spin.com'
  , 'sainsburysentertainment.co.uk'
  , 'metacritic.com'
];