/*
 * shorteners.js: a flat list of the domains of known url shorteners
 * (C) 2013 Ayatii Limited
 */

var Shorteners = module.exports;

Shorteners.knownDomains = ['adcrun.ch',
						   'adf.ly',
						   'beam.to',					    
						   'bit.ly',
						   'bitl.in',
						   'bioweb.me',
						   'budurl.com',
						   'catchylink.com',
   						   'cli.gs',
   						   'cm23.tk',
   						   'crum.bs',
   						   'decenturl.com',
   						   'deck.ly',
   						   'doiop.com',
   						   'digbig.com',
   						   'exc.lu',
						   'goo.gl',
						   'is.gd',
   						   'ity.im',
   						   'l.gg',
						   'minilien.com',   						   
   						   'moourl.com',
						   'notlong.com',
						   'ow.ly',
						   'para.pt',
						   'rdlnk.co',
						   'safelinking.net',
						   'shim.net',
						   'shorl.com',
						   'sn.im',
						   'snipr.com',
						   'su.pr',
						   'tiny.cc',
						   'tinyurl.com',
						   'to.ly',
						   'twurl.nl',
						   'tighturl.com',
						   'url.co.uk',
						   'yep.it',
						   'beam.to',
						   'xrl.us',
						   'xurls.co']
